### ISSUE TITLE
dd-agent BOSH job does not stop properly

### ISSUE THREAD

**Issue by teddyking** [DataDog/datadog-agent-boshrelease#34]
**Steps to reproduce the issue:**

1. Deploy datadog-agent/2.3.611
2. Run `monit stop datadog-agent`
3. Run `ps auxf`

**Describe the results you received:**

```
root      484261  0.4  0.0  18252  3204 ?        S<   12:37   0:01 bash /var/vcap/jobs/dd-agent/bin/agent_ctl stop
root      487837  0.0  0.0   4356   648 ?        S<   12:43   0:00  \_ sleep 0.1
```

The `agent_ctl stop` and child `sleep 0.1` processes continue running after issuing a `monit stop`. These processes build up each time a bosh deployment occurs (as presumably the agent is restarted each time, but never actually completes the shutdown).

**Describe the results you expected:**

I would expect to not see any processes related to the dd-agent BOSH job (including the sleep 0.1) left running on the system.

Note that the _actual_ datadog agent process does appear to terminate correctly.

**Comment by ostenbom** [comment]
👍 Still a problem!

**Comment by colmtuohy** [comment]
I see the same issue, during a delete-vm

**Comment by gmmeyer** [comment]
This should be resolved now!

**Comment by gmmeyer** [comment]
Thanks all, let me know if there is still an issue with this. :)
