### ISSUE TITLE
Trace agent generates errors.

### ISSUE THREAD

**Issue by mattjbarlow** [DataDog/datadog-agent-boshrelease#48]
**Steps to reproduce the issue:**
1. Install the datadog-agent-boshrelease.
2. Set  dd.trace_agent to "yes".
3. Check logs in `/var/vcap/sys/log/dd-agent/trace_agent.stderr.log`

**Describe the results you received:**
```
diego_cell/3e3b0a39-fe98-47d0-860f-3bc108345f54:/var/vcap/sys/log/dd-agent# head trace_agent.stderr.log 
seelog internal error: mkdir /var/log/datadog/: permission denied
seelog internal error: mkdir /var/log/datadog/: permission denied
seelog internal error: mkdir /var/log/datadog/: permission denied
seelog internal error: mkdir /var/log/datadog/: permission denied
```

**Describe the results you expected:**
No errors in the trace_agent.stderr.log

Process is owned by vcap user which does not have permissions in `/var/log` and there is no `/var/log/datadog` directory.

**Comment by gmmeyer** [comment]
This is definitely a bug! Thanks for the report. I'll put fixing this on our backlog.
