### ISSUE TITLE
dd-agent/datadog-agent_6.9.0-1_amd64.deb missing when creating bosh release

### ISSUE THREAD

**Issue by donghoang89** [DataDog/datadog-agent-boshrelease#73]
**Steps to reproduce the issue:**
1. Clone datadog-agent-boshrelease
2. Run "bosh create-release --name dd-agent --tarball=dd-agent-0.0.1.tgz"

**Describe the results you received:**

```
 05:12 PM:~/datadog-agent-boshrelease $ bosh create-release --name dd-agent --tarball=dd-agent-deploy-0.0.1.tgz
Building a release from directory '/Users/donghoang/calculi/datadog-agent-boshrelease':
  - Constructing packages from directory:
      - Reading package from '/Users/donghoang/calculi/datadog-agent-boshrelease/packages/dd-agent':
          Collecting package files:
            Missing files for pattern 'dd-agent/datadog-agent_6.9.0-1_amd64.deb'
  - Constructing jobs from manifest:
      - Expected to find package 'dd-agent' since it's a dependency of job 'dd-agent'

Exit code 1
```

**Describe the results you expected:**

Bosh create-release command succeeds and the tgz file is created.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by gzussa** [comment]
Hi @donghoang89. Sorry for the late answer. Do you still need to create a BOSH release yourself? This is something we do on our end. If you are looking for a more up to date version, you can check out our latest tile. If you want to do something else, I would be interested to understand what you are trying to achieve. Thanks

**Comment by gzussa** [comment]
I just took a deeper look at this. Starting with release made for Agent 6.10, the command works. 
Indeed, before that, we didn’t systematically upload deb artifacts. Since 6.10, we do. As a consequence I am closing this issue.
