### ISSUE TITLE
missing datadog.conf and dead symlinks

### ISSUE THREAD

**Issue by skertz** [DataDog/datadog-agent-boshrelease#76]
**Steps to reproduce the issue:**
1. When using Datadog 2.6.1 tile in PCF  which uses
datadog-agent                      2.6.690*  

We find that /var/vcap/jobs/dd-agent/config/datadog.conf is missing and the code to recreate 2 symlinks tto this file create dead links
 
``` rm -rf conf.d datadog.conf
  # create the links to the configuration
  ln -s /var/vcap/jobs/$JOB_NAME/config/conf.d conf.d
  ln -s /var/vcap/jobs/$JOB_NAME/config/datadog.conf datadog.conf
  ln -s /var/vcap/jobs/$JOB_NAME/config/datadog.yaml datadog.yaml
```

The deadlinks do no cause issues with the datadog agent itself, however, when using PCF's RabbitMQ it does. This deployment runs the following code during its errands on the rabbitmq-broker that attempts to perform chown -LR on directores. The -L is to traverse symlinks. This in turn errors and the deployment fails. To work around this issue, we either delete the 2 symlinks or "touch" the missing file.  

**Describe the results you received:**
```
++ chown -LR vcap:vcap /var/vcap/jobs/broker-registrar 
chown: cannot dereference '/var/vcap/jobs/broker-registrar/packages/dd-agent/agent/datadog.conf': No such file or directory 
chown: cannot dereference '/var/vcap/jobs/broker-registrar/packages/dd-agent/bin/agent/dist/datadog.conf': No such file or directory
```
**Describe the results you expected:**
We would expect that the missing file be included or to remove the symlinks to a missing file

**Comment by zippolyte** [comment]
This has been fixed in 2.7.6100. See https://github.com/DataDog/datadog-agent-boshrelease/releases/tag/2.7.6100 and https://github.com/DataDog/datadog-agent-boshrelease/pull/77.
Closing
