### ISSUE TITLE
Prometheus check is an unknown check

### ISSUE THREAD

**Issue by jboyens** [DataDog/datadog-agent-boshrelease#87]
**Steps to reproduce the issue:**
1. Install the dd-agent job
2. Configure a basic prometheus check
3. run `/var/vcap/packages/dd-client/bin/agent/agent status` and see that your prometheus check is not found in the catalog

**Describe the results you expected:**
If I run an Ubuntu docker container and install the agent, the prometheus check works fin.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by jboyens** [comment]
Debugging this, it's missing the Google Protobuf library. I was able to fix this by creating a symlink from `/var/vcap/packages/dd-agent` to `/opt/datadog-agent` I think the embedded Python may have some broken package paths

**Comment by zippolyte** [comment]
Hey, thanks for reporting and the investigation !
I'm having a look at it and indeed the packaging of the google protobuf python library makes it so that even by setting the correct PYTHONPATH while invoking the agent, it is not able to import it.
I'll figure out something to make it work.
